version: '3.8'

services:
  film-app:
    build: ./
    command: ./film-app
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - DB_PASSWORD=110513
      - DB_HOST=postgres
      - REDIS_HOST=redis
  db:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=110513
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5436:5432
    volumes:
      - ./film-app-data:/var/lib/postgresql/data
      - ./schema/000001_init.up.sql:/docker-entrypoint-initdb.d/000001_init.up.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:latest
    ports:
      - 6379:6379
volumes:
  film-app-data: