port: "8080"

db:
    username: "postgres"
    host: "localhost"
    port: "5436"
    dbname: "postgres"
    sslmode: "disable"

admin:
    id: 1
    login: "admin"
    password: "admin"
    age: "admin"